#!/usr/bin/env python3
"""
Plot Fig. 1: Safe vs Legacy residual perturbation dynamics.

Input CSVs are generated by CoOpPriorRes after applying the residual logging patch.
Expected columns include: epoch, lambda_t, residual_norm, relative_residual_norm,
safe_residual_norm, legacy_residual_norm, legacy_init_bias_relative_norm.
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict

import pandas as pd
import matplotlib.pyplot as plt


def read_curve(csv_path: Path, label: str, metric: str, reduce: str) -> pd.DataFrame:
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV not found: {csv_path}")

    df = pd.read_csv(csv_path)
    if "epoch" not in df.columns:
        raise ValueError(f"{csv_path} does not contain column: epoch")
    if metric not in df.columns:
        raise ValueError(
            f"{csv_path} does not contain metric column: {metric}\n"
            f"Available columns: {', '.join(df.columns)}"
        )

    numeric_cols = [c for c in df.columns if c not in []]
    for c in numeric_cols:
        df[c] = pd.to_numeric(df[c], errors="coerce")

    if reduce == "mean":
        agg_dict: Dict[str, str] = {metric: "mean"}
        for optional in [
            "lambda_t",
            "safe_relative_residual_norm",
            "legacy_relative_residual_norm",
            "legacy_init_bias_relative_norm",
            "safe_raw_residual_norm",
            "legacy_raw_residual_norm",
            "acc",
            "loss",
        ]:
            if optional in df.columns:
                agg_dict[optional] = "mean"
        out = df.groupby("epoch", as_index=False).agg(agg_dict)
    elif reduce == "last":
        sort_cols = ["epoch"]
        if "batch_idx" in df.columns:
            sort_cols.append("batch_idx")
        out = df.sort_values(sort_cols).groupby("epoch", as_index=False).tail(1)
    else:
        raise ValueError(f"Unsupported reduce mode: {reduce}")

    out = out.sort_values("epoch").reset_index(drop=True)
    out["label"] = label
    return out


def summarize_curve(df: pd.DataFrame, metric: str) -> str:
    label = str(df["label"].iloc[0])
    nonzero = df[df.get("lambda_t", pd.Series([1] * len(df))) > 0]
    if len(nonzero) > 0:
        first_active_epoch = int(nonzero["epoch"].iloc[0])
        first_active_value = float(nonzero[metric].iloc[0])
    else:
        first_active_epoch = -1
        first_active_value = float("nan")
    return (
        f"{label}: first_active_epoch={first_active_epoch}, "
        f"first_active_{metric}={first_active_value:.6g}, "
        f"max_{metric}={float(df[metric].max()):.6g}, "
        f"final_{metric}={float(df[metric].iloc[-1]):.6g}"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--safe", required=True, type=Path, help="Path to Safe run analysis_stats.csv")
    parser.add_argument("--legacy", required=True, type=Path, help="Path to Legacy run analysis_stats.csv")
    parser.add_argument("--out", required=True, type=Path, help="Output figure path, e.g. outputs/figures/fig1.pdf")
    parser.add_argument(
        "--metric",
        default="relative_residual_norm",
        choices=[
            "residual_norm",
            "relative_residual_norm",
            "safe_residual_norm",
            "legacy_residual_norm",
            "safe_relative_residual_norm",
            "legacy_relative_residual_norm",
            "safe_raw_residual_norm",
            "legacy_raw_residual_norm",
            "legacy_init_bias_relative_norm",
        ],
        help="Metric to plot on y-axis",
    )
    parser.add_argument("--reduce", default="mean", choices=["mean", "last"], help="Aggregate per epoch")
    parser.add_argument("--title", default="Residual Perturbation Dynamics", help="Figure title")
    parser.add_argument("--warmup-epochs", type=int, default=5, help="Draw vertical line at warmup boundary")
    parser.add_argument("--ramp-epochs", type=int, default=10, help="Draw vertical line at ramp completion")
    parser.add_argument("--show-init-bias", action="store_true", help="Overlay legacy_init_bias_relative_norm if available")
    args = parser.parse_args()

    safe = read_curve(args.safe, "Safe PriorRes", args.metric, args.reduce)
    legacy = read_curve(args.legacy, "Legacy PriorRes", args.metric, args.reduce)

    args.out.parent.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(7.2, 4.6))
    for df in [safe, legacy]:
        plt.plot(df["epoch"], df[args.metric], marker="o", linewidth=2, markersize=3.5, label=df["label"].iloc[0])

    # Optional: show the legacy formula's non-identity bias without lambda_t.
    if args.show_init_bias and "legacy_init_bias_relative_norm" in safe.columns:
        plt.plot(
            safe["epoch"],
            safe["legacy_init_bias_relative_norm"],
            linestyle="--",
            linewidth=1.6,
            label="Legacy init bias, no lambda",
        )

    if args.warmup_epochs > 0:
        plt.axvline(args.warmup_epochs, linestyle=":", linewidth=1.2, label="warmup end")
    if args.ramp_epochs > 0:
        plt.axvline(args.warmup_epochs + args.ramp_epochs, linestyle="--", linewidth=1.2, label="ramp end")

    ylabel = args.metric.replace("_", " ")
    plt.xlabel("Epoch")
    plt.ylabel(ylabel)
    plt.title(args.title)
    plt.grid(True, alpha=0.3)
    plt.legend(frameon=False)
    plt.tight_layout()

    plt.savefig(args.out, bbox_inches="tight", dpi=300)
    if args.out.suffix.lower() != ".png":
        png_path = args.out.with_suffix(".png")
        plt.savefig(png_path, bbox_inches="tight", dpi=300)
    else:
        pdf_path = args.out.with_suffix(".pdf")
        plt.savefig(pdf_path, bbox_inches="tight")

    print("[OK] saved", args.out)
    if args.out.suffix.lower() != ".png":
        print("[OK] saved", args.out.with_suffix(".png"))
    else:
        print("[OK] saved", args.out.with_suffix(".pdf"))
    print(summarize_curve(safe, args.metric))
    print(summarize_curve(legacy, args.metric))


if __name__ == "__main__":
    main()
